package cwhu.dllSolibLoad.lib.model.struct;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : line 3</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class RPPlaceJNA extends Structure {
	/** C type : Coord3DJNA */
	public Coord3DJNA coord;
	public double angle;
	public RPPlaceJNA() {
		super();
	}
	@Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("coord", "angle");
	}
	/** @param coord C type : Coord3DJNA */
	public RPPlaceJNA(Coord3DJNA coord, double angle) {
		super();
		this.coord = coord;
		this.angle = angle;
	}
	public static class ByReference extends RPPlaceJNA implements Structure.ByReference {

	};
	public static class ByValue extends RPPlaceJNA implements Structure.ByValue {

	};
}

